let user, profile, accounts=[], reports=[], closures=[], staff=[], messages=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===id));closeMenu();document.querySelector('.topbar')?.classList.remove('nav-hidden');window.scrollTo(0,0);if(id==='accounts')renderAccounts();if(id==='reports')renderReports();if(id==='closures')renderClosures();if(id==='archive')renderArchive();if(id==='staff')renderStaff();}
$$('.nav[data-view]').forEach(n=>n.addEventListener('click',()=>showView(n.dataset.view)));
function openAdminProfile(){
  if(!profile)return;
  const name=SANAD.esc(profile.full_name||profile.username||user?.email||'غير محدد');
  const username=SANAD.esc(profile.username||'—');
  const phone=SANAD.esc(profile.phone||'—');
  const email=SANAD.esc(profile.email||user?.email||'—');
  const role=profile.role==='admin'?'الإدارة العليا':`موظف ${SANAD.esc(profile.center_category||'')}`;
  const center=SANAD.esc(profile.center_category||'عام');
  $('#modalBody').innerHTML=`<div class="profile-panel"><div class="profile-hero"><div class="profile-avatar"><span class="material-symbols-rounded">admin_panel_settings</span></div><div><span class="eyebrow">الملف الشخصي</span><h2>${name}</h2><p class="help">${role}</p></div></div><div class="profile-grid"><div class="profile-field"><span class="material-symbols-rounded">alternate_email</span><div><small>اسم المستخدم</small><strong>${username}</strong></div></div><div class="profile-field"><span class="material-symbols-rounded">business</span><div><small>مركز العمل</small><strong>${center}</strong></div></div><div class="profile-field"><span class="material-symbols-rounded">call</span><div><small>رقم الهاتف</small><strong>${phone}</strong></div></div><div class="profile-field"><span class="material-symbols-rounded">mail</span><div><small>البريد الإلكتروني</small><strong>${email}</strong></div></div></div><div class="profile-note"><span class="material-symbols-rounded">verified</span><span>هذا الحساب معتمد وله صلاحيات مرتبطة بدوره داخل النظام.</span></div></div>`;
  $('#modal').classList.add('show');
}
function roleLabel(r){return r==='admin'?'الإدارة العليا':'موظف مركز';}
function statusClass(s){return s==='closed'?'status-green':s==='closure_requested'?'status-yellow':s==='rejected'?'status-red':'status-blue';}
async function init(){
  const s=await requireSession();if(!s)return;user=s.user;
  const {data:p,error}=await sb.from('profiles').select('*').eq('id',user.id).single();
  if(error||!p||!['admin','staff'].includes(p.role)||p.account_status!=='approved'){await sb.auth.signOut();location.href='login.html';return}
  profile=p;$('#adminName').textContent=p.full_name||p.username||user.email;$('#adminRole').textContent=p.role==='admin'?'الإدارة العليا':'موظف '+(p.center_category||'');
  if(p.role==='staff'){$$('.admin-only').forEach(x=>x.remove());showView('reports');}
  await loadAll();subscribeRealtime();
}
async function loadAll(){
  const queries=[
    profile.role==='admin'?sb.from('profiles').select('*').eq('role','student').order('created_at',{ascending:false}):Promise.resolve({data:[]}),
    sb.from('reports').select('*').order('created_at',{ascending:false}),
    sb.from('reports').select('*').eq('status','closure_requested').order('closure_requested_at',{ascending:false}),
    sb.from('profiles').select('*').eq('role','staff').order('full_name'),
  ];
  const [a,r,c,s]=await Promise.all(queries);accounts=a.data||[];reports=r.data||[];closures=c.data||[];staff=s.data||[];renderDashboard();if(profile.role==='admin')renderAccounts();renderReports();renderClosures();renderArchive();renderStaff();updateStaffQueue();
}
function renderDashboard(){
  const pending=accounts.filter(x=>x.account_status==='pending').length;
  $('#pendingAccounts').textContent=pending;$('#activeReports').textContent=reports.filter(x=>!['closed','rejected'].includes(x.status)).length;$('#closureRequests').textContent=closures.length;$('#closedReports').textContent=reports.filter(x=>x.status==='closed').length;
  const counts=Object.fromEntries(SANAD.categories.map(c=>[c,reports.filter(r=>r.category===c&&!['closed','rejected'].includes(r.status)).length]));
  $('#queues').innerHTML=SANAD.categories.map(c=>`<div class="q"><span><span class="material-symbols-rounded picker-icon">${SANAD.categoryIcons[c]}</span><span>${c}</span></span><b>${counts[c]}</b></div>`).join('');
  $('#dashboardReports').innerHTML=reports.slice(0,5).map(adminReportRow).join('')||'<p class="help">لا توجد بلاغات.</p>';
}
function adminReportRow(r){const ass=r.assigned_staff_name||'غير مستلم بعد';return `<div class="mini-row" onclick="openReport('${r.id}')"><div class="grow"><strong>${SANAD.esc(r.public_code)} — ${SANAD.esc(r.category)}</strong><small>${SANAD.esc(r.title||'بلاغ')} • ${SANAD.esc(ass)} • ${SANAD.formatDate(r.created_at)}</small></div><span class="status ${statusClass(r.status)}">${SANAD.statusLabels[r.status]||r.status}</span></div>`}
function accountRow(p){return `<div class="row" style="grid-template-columns:1.1fr 1fr 1fr .8fr .9fr"><div><strong>${SANAD.esc(p.full_name||'بدون اسم')}</strong><small style="display:block;color:#7c8691">${SANAD.esc(p.email||'')}</small></div><span>${SANAD.esc(p.institution_id||'—')}</span><span>${SANAD.esc(p.phone||'—')}</span><span class="status ${p.account_status==='approved'?'status-green':p.account_status==='rejected'?'status-red':'status-yellow'}">${p.account_status==='approved'?'معتمد':p.account_status==='rejected'?'مرفوض':'معلق'}</span><button class="secondary" onclick="reviewAccount('${p.id}')">مراجعة</button></div>`}
function renderAccounts(){const q=($('#accountSearch')?.value||'').toLowerCase();let data=accounts.filter(x=>(x.full_name||'').toLowerCase().includes(q)||(x.institution_id||'').toLowerCase().includes(q));$('#accountsList').innerHTML='<div class="row header" style="grid-template-columns:1.1fr 1fr 1fr .8fr .9fr"><span>الحساب</span><span>الهوية المؤسسية</span><span>الهاتف</span><span>الحالة</span><span>إجراء</span></div>'+(data.length?data.map(accountRow).join(''):'<div style="padding:25px;text-align:center;color:#87909b">لا توجد حسابات مطابقة.</div>')}
async function reviewAccount(id){const p=accounts.find(x=>x.id===id);if(!p)return;const urls=[];for(const path of [p.id_front_path,p.id_back_path]){if(path){const {data}=await sb.storage.from('id-documents').createSignedUrl(path,300);urls.push(data?.signedUrl)}}$('#modalBody').innerHTML=`<span class="eyebrow">مراجعة حساب</span><h2>${SANAD.esc(p.full_name)}</h2><p class="help">الرقم المؤسسي: ${SANAD.esc(p.institution_id||'—')}<br>الهاتف: ${SANAD.esc(p.phone||'—')}<br>البريد: ${SANAD.esc(p.email||'—')}</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:15px 0">${urls.map(u=>u?`<img src="${u}" style="width:100%;height:220px;object-fit:cover;border-radius:14px;border:1px solid #e5e8ec">`:'').join('')}</div><div class="form-actions"><button class="danger" onclick="rejectAccount('${id}')">رفض</button><button class="primary" onclick="approveAccount('${id}')">اعتماد الحساب</button></div>`;$('#modal').classList.add('show');}
async function approveAccount(id){const {error}=await sb.from('profiles').update({account_status:'approved',approved_at:new Date().toISOString(),rejection_reason:null}).eq('id',id);if(error){SANAD.toast(error.message);return}await sb.from('notifications').insert({user_id:id,title:'تم اعتماد حسابك',body:'يمكنك الآن الدخول إلى تطبيق عين الجامعة ورفع البلاغات.'});closeModal();SANAD.toast('تم اعتماد الحساب');await loadAll()}
async function rejectAccount(id){const reason=prompt('اكتب سبب رفض الحساب:');if(!reason?.trim())return;const {error}=await sb.from('profiles').update({account_status:'rejected',rejection_reason:reason.trim(),rejected_at:new Date().toISOString()}).eq('id',id);if(error){SANAD.toast(error.message);return}await sb.from('notifications').insert({user_id:id,title:'تم رفض طلب الحساب',body:`سبب الرفض: ${reason.trim()}`});closeModal();SANAD.toast('تم رفض الحساب مع تسجيل السبب');await loadAll()}
function renderReports(){const q=($('#reportSearch')?.value||'').toLowerCase();const activeFilter=document.querySelector('#reportFilters .active')?.dataset.filter||'all';let data=reports.filter(r=>(r.public_code||'').toLowerCase().includes(q)||(r.category||'').toLowerCase().includes(q));if(profile.role==='staff')data=data.filter(r=>!r.assigned_staff_id||r.assigned_staff_id===user.id);if(activeFilter!=='all')data=data.filter(r=>r.status===activeFilter);$('#reportFilters').innerHTML=[['all','الكل'],['submitted','غير مستلم'],['assigned','مستلم'],['in_progress','قيد المعالجة'],['closure_requested','طلب إغلاق'],['closed','مغلق']].map(([f,t])=>`<button data-filter="${f}" class="${f===activeFilter?'active':''}" onclick="setReportFilter('${f}')">${t}</button>`).join('');$('#reportsList').innerHTML='<div class="row header"><span>رقم البلاغ</span><span>المسار</span><span>المبلغ</span><span>الاستلام</span><span>الحالة</span></div>'+(data.length?data.map(r=>`<div class="row" onclick="openReport('${r.id}')"><strong>${SANAD.esc(r.public_code)}</strong><span>${SANAD.esc(r.category)}</span><span>${SANAD.esc(r.reporter_phone||'—')}</span><span>${r.assigned_staff_name?SANAD.esc(r.assigned_staff_name):'<b style="color:#b07900">غير مستلم</b>'}</span><span class="status ${statusClass(r.status)}">${SANAD.statusLabels[r.status]||r.status}</span></div>`).join(''):'<div style="padding:25px;text-align:center;color:#87909b">لا توجد بلاغات.</div>')}
function setReportFilter(f){$$('#reportFilters button').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderReports()}
function renderClosures(){$('#closuresList').innerHTML='<div class="row header"><span>الرقم</span><span>المسار</span><span>الموظف</span><span>وقت الطلب</span><span>إجراء</span></div>'+(closures.length?closures.map(r=>`<div class="row"><strong>${SANAD.esc(r.public_code)}</strong><span>${SANAD.esc(r.category)}</span><span>${SANAD.esc(r.assigned_staff_name||'—')}</span><small>${SANAD.formatDate(r.closure_requested_at)}</small><button class="secondary" onclick="reviewClosure('${r.id}')">مراجعة</button></div>`).join(''):'<div style="padding:25px;text-align:center;color:#87909b">لا توجد طلبات إغلاق.</div>')}
function renderArchive(){const data=reports.filter(r=>r.status==='closed');$('#archiveList').innerHTML='<div class="row header"><span>الرقم</span><span>المسار</span><span>العنوان</span><span>أُغلق في</span><span>الإجمالي</span></div>'+(data.length?data.map(r=>`<div class="row" onclick="openReport('${r.id}')"><strong>${SANAD.esc(r.public_code)}</strong><span>${SANAD.esc(r.category)}</span><span>${SANAD.esc(r.title||'بلاغ')}</span><small>${SANAD.formatDate(r.closed_at)}</small><span>${r.resolution_minutes?Math.round(r.resolution_minutes)+' د':'—'}</span></div>`).join(''):'<div style="padding:25px;text-align:center;color:#87909b">الأرشيف فارغ.</div>')}
async function reviewClosure(id){const r=reports.find(x=>x.id===id);if(!r)return;let photos='';for(const p of (r.resolution_photo_paths||[])){const {data}=await sb.storage.from('resolution-photos').createSignedUrl(p,300);if(data?.signedUrl)photos+=`<img src="${data.signedUrl}" style="width:100%;height:180px;object-fit:cover;border-radius:13px">`}$('#modalBody').innerHTML=`<span class="eyebrow">طلب إغلاق</span><h2>${SANAD.esc(r.public_code)}</h2><p class="help">الموظف: ${SANAD.esc(r.assigned_staff_name||'—')}<br>${SANAD.esc(r.description)}</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0">${photos||'<span class="help">لا توجد صور إنجاز.</span>'}</div><div class="form-actions"><button class="danger" onclick="rejectClosure('${id}')">رفض الطلب</button><button class="primary" onclick="approveClosure('${id}')">اعتماد الإغلاق</button></div>`;$('#modal').classList.add('show')}
async function approveClosure(id){const now=new Date().toISOString(),r=reports.find(x=>x.id===id);if(!r)return;const minutes=Math.max(0,Math.round((new Date(now)-new Date(r.created_at))/60000));const {error}=await sb.from('reports').update({status:'closed',closed_at:now,resolution_minutes:minutes}).eq('id',id);if(error){SANAD.toast(error.message);return}await sb.from('report_updates').insert({report_id:id,actor_id:user.id,title:'تم اعتماد الإغلاق',body:'وافقت الإدارة العليا على إغلاق البلاغ وأرشفته.',status:'closed'});await notifyReporter(id,'تم إغلاق البلاغ',`تم اعتماد إغلاق البلاغ ${r.public_code}.`);closeModal();await loadAll();SANAD.toast('تم اعتماد الإغلاق وأرشفة البلاغ')}
async function rejectClosure(id){const note=prompt('الملاحظات المطلوبة قبل إعادة المعالجة:');if(!note?.trim())return;const {error}=await sb.from('reports').update({status:'in_progress',closure_rejection_note:note.trim()}).eq('id',id);if(error){SANAD.toast(error.message);return}await sb.from('report_updates').insert({report_id:id,actor_id:user.id,title:'رُفض طلب الإغلاق',body:note.trim(),status:'in_progress'});await notifyReporter(id,'طلب الإغلاق يحتاج معالجة إضافية',note.trim());closeModal();await loadAll();SANAD.toast('تم رفض طلب الإغلاق وإعادته للمعالجة')}
async function notifyReporter(reportId,title,body){const r=reports.find(x=>x.id===reportId);if(r)await sb.from('notifications').insert({user_id:r.reporter_id,report_id:reportId,title,body})}
async function claimReport(id){if(profile.role!=='staff'){SANAD.toast('الاستلام متاح للموظف المختص فقط');return}const r=reports.find(x=>x.id===id);if(!r)return;if(r.assigned_staff_id&&r.assigned_staff_id!==user.id){SANAD.toast('هذا البلاغ مستلم بواسطة موظف آخر');return}const now=new Date().toISOString();const {error}=await sb.from('reports').update({assigned_staff_id:user.id,assigned_staff_name:profile.full_name||profile.username,assigned_at:now,status:r.status==='submitted'?'assigned':r.status}).eq('id',id).is('assigned_staff_id',null);if(error){SANAD.toast(error.message);return}await sb.from('report_updates').insert({report_id:id,actor_id:user.id,title:'تم استلام البلاغ',body:`استلم الموظف ${profile.full_name||profile.username} البلاغ للتعامل معه.`,status:'assigned'});await notifyReporter(id,'تم استلام البلاغ','تم استلام البلاغ من الموظف المختص وسيبدأ التعامل معه.');await loadAll();openReport(id);SANAD.toast('تم استلام البلاغ لك بنجاح')}
async function assignReport(id){if(profile.role!=='admin')return;const staffId=$('#assignStaff')?.value;if(!staffId){SANAD.toast('اختر الموظف المختص');return}const person=staff.find(s=>s.id===staffId),now=new Date().toISOString();const {error}=await sb.from('reports').update({assigned_staff_id:staffId,assigned_staff_name:person.full_name||person.username,assigned_at:now,status:'assigned'}).eq('id',id);if(error){SANAD.toast(error.message);return}await sb.from('report_updates').insert({report_id:id,actor_id:user.id,title:'تم تحويل البلاغ',body:`تم تحويل البلاغ إلى ${person.full_name||person.username} في مركز ${person.center_category}.`,status:'assigned'});await notifyReporter(id,'تم تحويل البلاغ إلى المركز المختص',`البلاغ أصبح لدى مركز ${person.center_category}.`);await sb.from('notifications').insert({user_id:staffId,report_id:id,title:'بلاغ جديد للمركز',body:`تم تحويل البلاغ ${reports.find(x=>x.id===id)?.public_code||''} إليك لمعالجته.`});closeModal();await loadAll();SANAD.toast('تم تحويل البلاغ بنجاح')}
async function startReport(id){const r=reports.find(x=>x.id===id);if(!r||profile.role!=='staff'||r.assigned_staff_id!==user.id){SANAD.toast('لا يمكنك معالجة هذا البلاغ قبل استلامه');return}const now=new Date().toISOString();const {error}=await sb.from('reports').update({status:'in_progress',in_progress_at:now}).eq('id',id).eq('assigned_staff_id',user.id);if(error){SANAD.toast(error.message);return}await sb.from('report_updates').insert({report_id:id,actor_id:user.id,title:'بدأت المعالجة الميدانية',body:'الموظف المختص بدأ التعامل مع البلاغ.',status:'in_progress'});await notifyReporter(id,'بدأت معالجة بلاغك','الفريق المختص بدأ المعالجة الميدانية.');await loadAll();openReport(id);SANAD.toast('تم تحديث البلاغ إلى قيد المعالجة')}
async function requestClosure(id){const r=reports.find(x=>x.id===id);if(!r||profile.role!=='staff'||r.assigned_staff_id!==user.id){SANAD.toast('يجب استلام البلاغ أولًا');return}const input=$('#resolutionFiles'),files=[...(input?.files||[])];if(files.length===0){SANAD.toast('أرفق صور الإنجاز قبل طلب الإغلاق');return}if(files.length>3){SANAD.toast('الحد الأقصى 3 صور');return}try{const paths=[];for(let i=0;i<files.length;i++){const path=`${user.id}/${r.public_code}/${i+1}-${Date.now()}.jpg`;const {error}=await sb.storage.from('resolution-photos').upload(path,files[i],{upsert:false,contentType:files[i].type});if(error)throw error;paths.push(path)}const now=new Date().toISOString();const {error}=await sb.from('reports').update({status:'closure_requested',resolution_photo_paths:paths,closure_requested_at:now}).eq('id',id).eq('assigned_staff_id',user.id);if(error)throw error;await sb.from('report_updates').insert({report_id:id,actor_id:user.id,title:'تم تقديم طلب الإغلاق',body:'تم رفع صور الإنجاز وإرسال الطلب إلى الإدارة العليا للاعتماد.',status:'closure_requested'});await notifyReporter(id,'تم تقديم طلب إغلاق بلاغك','الفريق المختص أنهى المعالجة ورفع صور الإنجاز، والبلاغ الآن بانتظار اعتماد الإدارة العليا.');closeModal();await loadAll();SANAD.toast('تم إرسال طلب الإغلاق للإدارة العليا')}catch(e){SANAD.toast(e.message||'تعذر رفع صور الإنجاز')}}
async function openReport(id){const r=reports.find(x=>x.id===id);if(!r)return;const [{data:updates},{data:st},{data:chat}]=await Promise.all([sb.from('report_updates').select('*').eq('report_id',id).order('created_at'),r.assigned_staff_id?sb.from('profiles').select('full_name,username,center_category').eq('id',r.assigned_staff_id).maybeSingle():Promise.resolve({data:null}),sb.from('report_messages').select('id,report_id,sender_id,body,created_at').eq('report_id',id).order('created_at')]);messages=chat||[];let actions='';
  if(profile.role==='admin'){const people=staff.filter(s=>s.center_category===r.category&&s.account_status==='approved');actions=`<div class="field" style="margin-top:16px"><label>الموظف المستلم الحالي</label><select id="assignStaff"><option value="">اختر موظفًا</option>${people.map(s=>`<option value="${s.id}" ${s.id===r.assigned_staff_id?'selected':''}>${SANAD.esc(s.full_name||s.username)}</option>`).join('')}</select></div><div class="form-actions"><button class="primary" onclick="assignReport('${id}')">حفظ التحويل</button></div>`;
  } else if(!r.assigned_staff_id){actions=`<div class="claim-box"><strong>البلاغ غير مستلم</strong><span>لن تستطيع كتابة الشات أو بدء المعالجة قبل استلامه.</span><button class="primary" onclick="claimReport('${id}')">استلام البلاغ</button></div>`;
  } else if(r.assigned_staff_id===user.id){actions=`<div style="margin-top:18px" class="field"><label>صور الإنجاز (حتى 3)</label><input id="resolutionFiles" type="file" accept="image/*" multiple></div><div class="form-actions"><button class="secondary" onclick="startReport('${id}')">بدء/متابعة المعالجة</button><button class="primary" onclick="requestClosure('${id}')">طلب إغلاق</button></div>`;
  } else {actions=`<div class="claim-box"><strong>البلاغ مستلم بواسطة موظف آخر</strong><span>${SANAD.esc(r.assigned_staff_name||'موظف آخر')} • لا يمكنك تعديل البلاغ أو الكتابة في الشات.</span></div>`;}
  const canChat=profile.role==='admin'||r.assigned_staff_id===user.id;const chatHtml=`<div class="chat-box"><div class="panel-head"><h3>شات البلاغ</h3><span class="status ${canChat?'status-green':'status-yellow'}">${canChat?'مفتوح لك':'مغلق حتى الاستلام'}</span></div><div class="chat-list">${messages.length?messages.map(m=>`<div class="chat-msg ${m.sender_id===user.id?'mine':''}"><strong>${m.sender_id===user.id?'أنت':'مستخدم إداري'}</strong><span>${SANAD.esc(m.body)}</span><small>${SANAD.formatDate(m.created_at)}</small></div>`).join(''):'<div class="help">لا توجد رسائل بعد.</div>'}</div>${canChat?`<div class="chat-compose"><textarea id="chatBody" rows="2" placeholder="اكتب تحديثًا أو ملاحظة للمتابعين..."></textarea><button class="primary" onclick="sendMessage('${id}')">إرسال</button></div>`:'<div class="help">استلم البلاغ أولًا لتفعيل الشات.</div>'}</div>`;
  $('#modalBody').innerHTML=`<span class="eyebrow">ملف البلاغ</span><h2>${SANAD.esc(r.public_code)}</h2><p class="help">المسار: ${SANAD.esc(r.category)}<br>الموقع: ${r.latitude?`${r.latitude}, ${r.longitude}`:'غير متاح'}<br>الحالة: <span class="status ${statusClass(r.status)}">${SANAD.statusLabels[r.status]||r.status}</span><br>المستلم: ${SANAD.esc(st?.full_name||st?.username||'لم يستلم بعد')}</p><div style="background:#fafbfc;padding:13px;border-radius:14px;margin:12px 0;font-size:12px;line-height:1.9">${SANAD.esc(r.description)}</div><div class="timeline">${(updates||[]).map(u=>`<div class="timeline-item"><strong>${SANAD.esc(u.title)}</strong><span>${SANAD.esc(u.body||'')}<br>${SANAD.formatDate(u.created_at)}</span></div>`).join('')||'<div class="timeline-item"><strong>تم استلام البلاغ</strong><span>تم تسجيل البلاغ.</span></div>'}</div>${chatHtml}${actions}`;$('#modal').classList.add('show');}
async function sendMessage(reportId){const r=reports.find(x=>x.id===reportId);const body=$('#chatBody')?.value.trim();if(!body)return;if(profile.role!=='admin'&&r?.assigned_staff_id!==user.id){SANAD.toast('استلم البلاغ أولًا قبل الكتابة');return}const {error}=await sb.from('report_messages').insert({report_id:reportId,sender_id:user.id,body});if(error){SANAD.toast(error.message);return}await sb.from('report_updates').insert({report_id:reportId,actor_id:user.id,title:'رسالة إدارية جديدة',body,status:r?.status||'assigned'});await openReport(reportId);}
function updateStaffQueue(){if(profile.role!=='staff')return;const mine=reports.filter(r=>r.assigned_staff_id===user.id).length;const free=reports.filter(r=>!r.assigned_staff_id&&r.category===profile.center_category&&![ 'closed','rejected'].includes(r.status)).length;const el=$('#staffPanel');if(el)el.dataset.queue=`متاح للاستلام: ${free} • مستلم لديك: ${mine}`;}
function renderStaff(){const admin=profile.role==='admin';const head=admin?`<div class="admin-create"><h3>إنشاء حساب إداري</h3><p class="help">إنشاء الحساب يتم من صفحة مستقلة، وبعد الإنشاء يسجل الموظف أو المدير الدخول بيوزر وكلمة مرور.</p><div class="form-actions"><a class="primary" href="register.html" style="text-decoration:none">إنشاء حساب جديد</a><a class="secondary" href="login.html" style="text-decoration:none">صفحة تسجيل الدخول</a></div></div>`:'';const cards=SANAD.categories.map(c=>{const people=staff.filter(s=>s.center_category===c);const free=reports.filter(r=>!r.assigned_staff_id&&r.category===c&&!['closed','rejected'].includes(r.status)).length;return `<div class="center-card"><div><strong><span class="material-symbols-rounded picker-icon">${SANAD.categoryIcons[c]}</span><span>${c}</span></strong><span class="status ${free?'status-yellow':'status-green'}">${free} بلاغ غير مستلم</span></div><p>${people.length?people.map(p=>`${SANAD.esc(p.full_name||p.username||'بدون اسم')} — ${p.account_status==='approved'?'نشط':'غير نشط'}`).join('<br>'):'لا يوجد موظفون'}</p></div>`}).join('');$('#staffPanel').innerHTML=head+`<div class="center-grid">${cards}</div>`;}
function subscribeRealtime(){sb.channel('admin-live').on('postgres_changes',{event:'*',schema:'public',table:'profiles'},()=>loadAll()).on('postgres_changes',{event:'*',schema:'public',table:'reports'},()=>loadAll()).on('postgres_changes',{event:'*',schema:'public',table:'report_messages'},()=>{}).subscribe();}
function closeModal(){$('#modal').classList.remove('show')}$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});async function logout(){await sb.auth.signOut();location.href='login.html'}
init();

/* ===== تنقل الهاتف + إظهار/إخفاء الشريط العلوي ===== */
function openMenu(){
  const sidebar=$('#sidebar'), backdrop=$('#menuBackdrop'), toggle=document.querySelector('.menu-toggle');
  sidebar?.classList.add('open'); backdrop?.classList.add('show'); document.body.classList.add('menu-open'); toggle?.setAttribute('aria-expanded','true');
}
function closeMenu(){
  const sidebar=$('#sidebar'), backdrop=$('#menuBackdrop'), toggle=document.querySelector('.menu-toggle');
  sidebar?.classList.remove('open'); backdrop?.classList.remove('show'); document.body.classList.remove('menu-open'); toggle?.setAttribute('aria-expanded','false');
}
function toggleMenu(){
  const open=$('#sidebar')?.classList.contains('open'); open?closeMenu():openMenu();
}
(function setupMobileNavigation(){
  let lastY=window.scrollY, ticking=false;
  const bar=document.querySelector('.topbar');
  function onScroll(){
    const y=Math.max(0,window.scrollY);
    if(bar && window.innerWidth<=650 && !document.body.classList.contains('menu-open')){
      if(y>lastY+12 && y>96) bar.classList.add('nav-hidden');
      else if(y<lastY-10 || y<20) bar.classList.remove('nav-hidden');
    }
    if(document.body.classList.contains('menu-open')) bar.classList.remove('nav-hidden');
    lastY=y;
  }
  window.addEventListener('scroll',()=>{if(!ticking){window.requestAnimationFrame(()=>{onScroll();ticking=false});ticking=true}}, {passive:true});
  window.addEventListener('resize',()=>{if(window.innerWidth>650) bar?.classList.remove('nav-hidden');});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
  document.addEventListener('click',e=>{if(e.target.closest('.sidebar .nav[data-view]')) closeMenu();});
})();
