-- شغّل هذا الملف على قاعدة عين الجامعة الحالية.
-- لا يحذف أي بيانات، ومصمم ليعمل حتى لو نفذت بعض أجزائه سابقًا.

alter table public.profiles add column if not exists username text;
create unique index if not exists profiles_username_unique on public.profiles(lower(username)) where username is not null;

create table if not exists public.report_messages (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.reports(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (length(trim(body)) between 1 and 2000),
  created_at timestamptz not null default now()
);
alter table public.report_messages enable row level security;

drop policy if exists report_messages_select on public.report_messages;
create policy report_messages_select on public.report_messages for select to authenticated using (
  exists(select 1 from public.reports r where r.id=report_id and (public.is_admin() or r.assigned_staff_id=auth.uid()))
);

drop policy if exists report_messages_insert on public.report_messages;
create policy report_messages_insert on public.report_messages for insert to authenticated with check (
  sender_id=auth.uid() and exists(select 1 from public.reports r where r.id=report_id and (public.is_admin() or r.assigned_staff_id=auth.uid()))
);

create or replace function public.lookup_login_email(username_input text)
returns text language sql security definer set search_path=public as $$
  select email from public.profiles
  where lower(username)=lower(trim(username_input))
    and role in ('admin','staff')
    and account_status='approved'
  limit 1;
$$;
revoke all on function public.lookup_login_email(text) from public;
grant execute on function public.lookup_login_email(text) to anon, authenticated;

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='report_messages') then
    execute 'alter publication supabase_realtime add table public.report_messages';
  end if;
end $$;


-- إصلاح إنشاء حسابات الإدارة: حسابات تطبيق الإدارة تُحفظ مباشرة كـ admin/staff معتمدة.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  requested_role text := lower(coalesce(new.raw_user_meta_data->>'role','student'));
  requested_center text := new.raw_user_meta_data->>'center_category';
  is_admin_signup boolean := coalesce((new.raw_user_meta_data->>'admin_registration')::boolean,false);
  final_role text := case when is_admin_signup and requested_role in ('admin','staff') then requested_role else 'student' end;
  final_status text := case when final_role in ('admin','staff') then 'approved' else 'pending' end;
begin
  insert into public.profiles(id,email,username,full_name,role,center_category,account_status,approved_at)
  values(
    new.id,
    new.email,
    lower(nullif(new.raw_user_meta_data->>'username','')),
    coalesce(new.raw_user_meta_data->>'full_name',''),
    final_role,
    case when final_role='staff' then requested_center else null end,
    final_status,
    case when final_status='approved' then now() else null end
  )
  on conflict (id) do update set
    email=excluded.email, username=excluded.username, full_name=excluded.full_name,
    role=excluded.role, center_category=excluded.center_category,
    account_status=excluded.account_status, approved_at=excluded.approved_at;
  return new;
end;
$$;

-- ملاحظة: هذا يجعل التسجيل الإداري المباشر متاحًا من تطبيق الإدارة. في الإنتاج يفضّل إضافة دعوة/كود إداري أو إنشاء الحساب عبر Edge Function بصلاحيات خادمية.
