-- سند | Supabase Database Setup
-- نفّذ الملف من SQL Editor في مشروع Supabase.
-- لا تضع service_role key في أي ملف Front-end.

create extension if not exists pgcrypto;

create sequence if not exists public.report_sequence start 1;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  username text unique,
  full_name text not null default '',
  institution_id text unique,
  phone text,
  role text not null default 'student' check (role in ('student','staff','admin')),
  center_category text check (center_category in ('الأمن','الإسعافات الطبية','الصيانة','الخدمات','الشكوى')),
  account_status text not null default 'pending' check (account_status in ('pending','approved','rejected')),
  rejection_reason text,
  id_front_path text,
  id_back_path text,
  sanad_points integer not null default 0 check (sanad_points >= 0),
  approved_at timestamptz,
  rejected_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  avatar_url text
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  public_code text not null unique,
  reporter_id uuid not null references public.profiles(id) on delete restrict,
  reporter_phone text,
  category text not null check (category in ('الأمن','الإسعافات الطبية','الصيانة','الخدمات','الشكوى')),
  title text not null default 'بلاغ',
  description text not null,
  latitude double precision,
  longitude double precision,
  location_accuracy double precision,
  photo_paths text[] not null default '{}',
  resolution_photo_paths text[] not null default '{}',
  status text not null default 'submitted' check (status in ('submitted','assigned','in_progress','closure_requested','closed','rejected')),
  assigned_staff_id uuid references public.profiles(id) on delete set null,
  assigned_staff_name text,
  closure_rejection_note text,
  created_at timestamptz not null default now(),
  assigned_at timestamptz,
  in_progress_at timestamptz,
  closure_requested_at timestamptz,
  closed_at timestamptz,
  resolution_minutes integer
);

create table if not exists public.report_updates (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.reports(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  title text not null,
  body text,
  status text,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  report_id uuid references public.reports(id) on delete cascade,
  title text not null,
  body text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.rewards (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  points_cost integer not null check (points_cost > 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin(uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=uid and p.role='admin' and p.account_status='approved');
$$;

create or replace function public.is_staff(uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=uid and p.role='staff' and p.account_status='approved');
$$;

create or replace function public.create_report_code()
returns text language plpgsql security definer set search_path=public as $$
declare n bigint;
begin
  n := nextval('public.report_sequence');
  return 'SN-' || to_char(now(),'YYYY') || '-' || lpad(n::text,6,'0');
end;
$$;
grant execute on function public.create_report_code() to authenticated;

create or replace function public.is_approved_student(uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=uid and p.role='student' and p.account_status='approved');
$$;
revoke all on function public.is_approved_student(uuid) from public;
grant execute on function public.is_approved_student(uuid) to authenticated;

create or replace function public.create_student_report(
  p_public_code text, p_category text, p_title text, p_description text,
  p_reporter_phone text default null, p_photo_paths text[] default '{}'::text[]
)
returns public.reports language plpgsql security definer set search_path=public as $$
declare inserted_report public.reports;
begin
  if auth.uid() is null or not public.is_approved_student(auth.uid()) then
    raise exception 'الحساب غير مصرح لإرسال البلاغات.';
  end if;
  if p_category not in ('الأمن','الإسعافات الطبية','الصيانة','الخدمات','الشكوى') then raise exception 'مسار البلاغ غير صالح.'; end if;
  if length(trim(coalesce(p_description,''))) < 10 then raise exception 'تفاصيل المشكلة قصيرة جدًا.'; end if;
  insert into public.reports(public_code,reporter_id,category,title,description,reporter_phone,photo_paths,status)
  values(p_public_code,auth.uid(),p_category,coalesce(nullif(trim(p_title),''),'بلاغ'),trim(p_description),p_reporter_phone,coalesce(p_photo_paths,'{}'::text[]),'submitted')
  returning * into inserted_report;
  return inserted_report;
end; $$;
revoke all on function public.create_student_report(text,text,text,text,text,text[]) from public;
grant execute on function public.create_student_report(text,text,text,text,text,text[]) to authenticated;


create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists trg_profiles_updated on public.profiles;
create trigger trg_profiles_updated before update on public.profiles for each row execute function public.touch_updated_at();

-- حسابات جديدة: إذا كانت metadata تحمل الاسم، يتم إنشاء profile تلقائيًا.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  requested_username text := lower(nullif(trim(new.raw_user_meta_data->>'username'),''));
  requested_center text := nullif(trim(new.raw_user_meta_data->>'center_category'),'');
  -- Never trust role/admin flags supplied from the browser. Every new Auth user
  -- starts as a pending student; privileged promotion is handled by a guarded RPC.
  final_role text := 'student';
  final_status text := 'pending';
begin
  insert into public.profiles(id,email,username,full_name,role,center_category,account_status,approved_at)
  values(
    new.id,
    new.email,
    requested_username,
    coalesce(new.raw_user_meta_data->>'full_name',''),
    final_role,
    case when final_role='staff' then requested_center else null end,
    final_status,
    case when final_status='approved' then now() else null end
  )
  on conflict (id) do update set
    email=excluded.email,
    username=excluded.username,
    full_name=excluded.full_name,
    role=excluded.role,
    center_category=excluded.center_category,
    account_status=excluded.account_status,
    approved_at=excluded.approved_at;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.reports enable row level security;
alter table public.report_updates enable row level security;
alter table public.notifications enable row level security;
alter table public.rewards enable row level security;

-- Profiles
 drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated using (
  id=auth.uid() or public.is_admin() or (public.is_staff() and role='student')
);
drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles for insert to authenticated with check (id=auth.uid() and role='student');
drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());
-- الطالب يستطيع استكمال بيانات ملفه فقط وهو ما يزال pending؛ لا يستطيع اعتماد نفسه.
drop policy if exists profiles_student_pending_update on public.profiles;
create policy profiles_student_pending_update on public.profiles for update to authenticated
using (id=auth.uid() and role='student' and account_status='pending')
with check (id=auth.uid() and role='student' and account_status='pending');

-- Reports
 drop policy if exists reports_select on public.reports;
create policy reports_select on public.reports for select to authenticated using (
  reporter_id=auth.uid()
  or public.is_admin()
  or (public.is_staff() and (assigned_staff_id=auth.uid() or (assigned_staff_id is null and category=(select p.center_category from public.profiles p where p.id=auth.uid()))))
);
drop policy if exists reports_insert on public.reports;
create policy reports_insert on public.reports for insert to authenticated with check (reporter_id=auth.uid() and public.is_approved_student(auth.uid()));
drop policy if exists reports_admin_update on public.reports;
create policy reports_admin_update on public.reports for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists reports_staff_update on public.reports;
create policy reports_staff_update on public.reports for update to authenticated using (public.is_staff() and assigned_staff_id=auth.uid()) with check (public.is_staff() and assigned_staff_id=auth.uid());

-- Updates
 drop policy if exists report_updates_select on public.report_updates;
create policy report_updates_select on public.report_updates for select to authenticated using (
  exists(select 1 from public.reports r where r.id=report_id and (r.reporter_id=auth.uid() or public.is_admin() or (public.is_staff() and r.assigned_staff_id=auth.uid())))
);
drop policy if exists report_updates_insert on public.report_updates;
create policy report_updates_insert on public.report_updates for insert to authenticated with check (
  actor_id=auth.uid() and exists(select 1 from public.reports r where r.id=report_id and (public.is_admin() or (public.is_staff() and r.assigned_staff_id=auth.uid())))
);

-- Notifications
drop policy if exists notifications_select on public.notifications;
create policy notifications_select on public.notifications for select to authenticated using (user_id=auth.uid() or public.is_admin());
drop policy if exists notifications_insert on public.notifications;
create policy notifications_insert on public.notifications for insert to authenticated with check (public.is_admin() or user_id=auth.uid());
drop policy if exists notifications_update on public.notifications;
create policy notifications_update on public.notifications for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

-- Rewards
drop policy if exists rewards_select on public.rewards;
create policy rewards_select on public.rewards for select to authenticated using (active=true or public.is_admin());
drop policy if exists rewards_admin on public.rewards;
create policy rewards_admin on public.rewards for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Storage buckets
insert into storage.buckets(id,name,public) values
 ('id-documents','id-documents',false),
 ('report-photos','report-photos',false),
 ('resolution-photos','resolution-photos',false),
 ('avatars','avatars',true)
on conflict (id) do nothing;

-- Storage permissions. First folder in each path is the user id.
drop policy if exists id_docs_select on storage.objects;
create policy id_docs_select on storage.objects for select to authenticated using (
  bucket_id='id-documents' and (public.is_admin() or (storage.foldername(name))[1]=auth.uid()::text)
);
drop policy if exists id_docs_insert on storage.objects;
create policy id_docs_insert on storage.objects for insert to authenticated with check (
  bucket_id='id-documents' and (storage.foldername(name))[1]=auth.uid()::text
);

drop policy if exists report_photos_select on storage.objects;
create policy report_photos_select on storage.objects for select to authenticated using (
  bucket_id='report-photos' and (
    public.is_admin()
    or (storage.foldername(name))[1]=auth.uid()::text
    or exists(select 1 from public.reports r where r.public_code=(storage.foldername(name))[2] and r.assigned_staff_id=auth.uid())
  )
);
drop policy if exists report_photos_insert on storage.objects;
create policy report_photos_insert on storage.objects for insert to authenticated with check (
  bucket_id='report-photos' and (storage.foldername(name))[1]=auth.uid()::text
);

-- Resolution photos are uploaded by the assigned employee. Admin can view.
drop policy if exists resolution_photos_select on storage.objects;
create policy resolution_photos_select on storage.objects for select to authenticated using (
  bucket_id='resolution-photos' and (public.is_admin() or (storage.foldername(name))[1]=auth.uid()::text)
);
drop policy if exists resolution_photos_insert on storage.objects;
create policy resolution_photos_insert on storage.objects for insert to authenticated with check (
  bucket_id='resolution-photos' and public.is_staff() and (storage.foldername(name))[1]=auth.uid()::text
);



-- Public profile avatars. The URL is public by design; profile data remains protected by RLS.
drop policy if exists avatars_insert on storage.objects;
create policy avatars_insert on storage.objects for insert to authenticated with check (
  bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text
);
drop policy if exists avatars_update on storage.objects;
create policy avatars_update on storage.objects for update to authenticated using (
  bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text
) with check (
  bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text
);
drop policy if exists avatars_delete on storage.objects;
create policy avatars_delete on storage.objects for delete to authenticated using (
  bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text
);

create or replace function public.set_profile_avatar(p_avatar_url text)
returns public.profiles language plpgsql security definer set search_path=public as $$
declare updated_profile public.profiles;
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول.'; end if;
  if p_avatar_url is null or length(trim(p_avatar_url)) < 10 then raise exception 'رابط الصورة غير صالح.'; end if;
  update public.profiles set avatar_url=trim(p_avatar_url), updated_at=now()
  where id=auth.uid()
  returning * into updated_profile;
  if updated_profile.id is null then raise exception 'تعذر تحديث صورة الملف.'; end if;
  return updated_profile;
end; $$;
revoke all on function public.set_profile_avatar(text) from public;
grant execute on function public.set_profile_avatar(text) to authenticated;

-- Realtime
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='reports') then execute 'alter publication supabase_realtime add table public.reports'; end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='report_updates') then execute 'alter publication supabase_realtime add table public.report_updates'; end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notifications') then execute 'alter publication supabase_realtime add table public.notifications'; end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='profiles') then execute 'alter publication supabase_realtime add table public.profiles'; end if;
end $$;

insert into public.rewards(name,points_cost)
select * from (values ('مشروب مجاني',500),('خصم خدمة جامعية',1000),('مكافأة مميزة',2000)) as v(name,points_cost)
where not exists (select 1 from public.rewards r where r.name=v.name);


-- إشعار الإدارة عند وصول بلاغ جديد.
create or replace function public.notify_admins_new_report()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.notifications(user_id,report_id,title,body)
  select p.id,new.id,'بلاغ جديد وارد', 'وصل البلاغ '||new.public_code||' إلى الإدارة العليا ضمن مسار '||new.category||'.'
  from public.profiles p
  where p.role='admin' and p.account_status='approved';
  return new;
end;
$$;
drop trigger if exists trg_report_notify_admins on public.reports;
create trigger trg_report_notify_admins after insert on public.reports for each row execute function public.notify_admins_new_report();

-- إشعار الإدارة عند طلب إنشاء حساب جديد.
create or replace function public.notify_admins_new_account()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.role='student' and new.account_status='pending' then
    insert into public.notifications(user_id,title,body)
    select p.id,'طلب حساب جامعي جديد','يوجد طلب حساب جديد باسم '||coalesce(new.full_name,'غير محدد')||'.'
    from public.profiles p
    where p.role='admin' and p.account_status='approved';
  end if;
  return new;
end;
$$;
drop trigger if exists trg_profile_notify_admins on public.profiles;
create trigger trg_profile_notify_admins after insert on public.profiles for each row execute function public.notify_admins_new_account();


-- عين الجامعة: نظام حسابات الإدارة والشات واستلام البلاغات (آمن لإعادة التشغيل)
alter table public.profiles add column if not exists username text;
create unique index if not exists profiles_username_unique on public.profiles(lower(username)) where username is not null;

create table if not exists public.report_messages (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.reports(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (length(trim(body)) between 1 and 2000),
  created_at timestamptz not null default now()
);
alter table public.report_messages enable row level security;
drop policy if exists report_messages_select on public.report_messages;
create policy report_messages_select on public.report_messages for select to authenticated using (
  exists(select 1 from public.reports r where r.id=report_id and (public.is_admin() or r.assigned_staff_id=auth.uid()))
);
drop policy if exists report_messages_insert on public.report_messages;
create policy report_messages_insert on public.report_messages for insert to authenticated with check (
  sender_id=auth.uid() and exists(select 1 from public.reports r where r.id=report_id and (public.is_admin() or r.assigned_staff_id=auth.uid()))
);

create or replace function public.lookup_login_email(username_input text)
returns text
language sql
security definer
set search_path=public
as $$
  select email from public.profiles where lower(username)=lower(trim(username_input)) and role in ('admin','staff') and account_status='approved' limit 1;
$$;
revoke all on function public.lookup_login_email(text) from public;
grant execute on function public.lookup_login_email(text) to anon, authenticated;

-- يسمح للمدير بإدخال بيانات حساب إداري بعد إنشاء مستخدم Auth.
drop policy if exists profiles_admin_insert on public.profiles;
create policy profiles_admin_insert on public.profiles for insert to authenticated with check (public.is_admin() and role in ('admin','staff'));

-- Realtime للشات بشكل آمن عند إعادة التنفيذ.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='report_messages') then execute 'alter publication supabase_realtime add table public.report_messages'; end if;
end $$;
